{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.kanata;

  inherit
    (config.lib.utils)
    escapeSystemdExecArgs
    ;

  upstreamDoc = "See [the upstream documentation](https://github.com/jtroo/kanata/blob/main/docs/config.adoc) and [example config files](https://github.com/jtroo/kanata/tree/main/cfg_samples) for more information.";

  configDir =
    if config.xdg.enable
    then "${config.xdg.configHome}/kanata"
    else "${config.home.homeDirectory}/.config/kanata";

  keyboard = {
    name,
    config,
    ...
  }: {
    options = {
      devices = mkOption {
        type = with types; listOf str;
        default = [];
        example = ["/dev/input/by-id/usb-0000_0000-event-kbd"];
        description = ''
          Paths to keyboard devices.

          An empty list, the default value, lets kanata detect which
          input devices are keyboards and intercept them all.
        '';
      };
      config = mkOption {
        type = types.lines;
        example = ''
          (defsrc
            caps)

          (deflayermap (default-layer)
            ;; tap caps lock as caps lock, hold caps lock as left control
            caps (tap-hold 100 100 caps lctl))
        '';
        description = ''
          Configuration other than `defcfg`.

          ${upstreamDoc}
        '';
      };
      extraDefCfg = mkOption {
        type = types.lines;
        default = "";
        example = "danger-enable-cmd yes";
        description = ''
          Configuration of `defcfg` other than `linux-dev` (generated
          from the devices option) and
          `linux-continue-if-no-devs-found` (hardcoded to be yes).

          ${upstreamDoc}
        '';
      };
      configFile = mkOption {
        type = types.path;
        default = mkConfig name config;
        defaultText = "A config file generated by values from other kanata module options.";
        description = ''
          The config file.

          By default, it is generated by values from other kanata
          module options.

          You can also set it to your own full config file which
          overrides all other kanata module options.  ${upstreamDoc}
        '';
      };
      extraArgs = mkOption {
        type = with types; listOf str;
        default = [];
        description = "Extra command line arguments passed to kanata.";
      };
      port = mkOption {
        type = with types; nullOr port;
        default = null;
        example = 6666;
        description = ''
          Port to run the TCP server on. `null` will not run the server.
        '';
      };
    };
  };

  mkName = name: "kanata-${name}";

  mkDevices = devices: let
    devicesString = pipe devices [
      (map (device: "\"" + device + "\""))
      (concatStringsSep " ")
    ];
  in
    optionalString ((length devices) > 0) "linux-dev (${devicesString})";

  mkConfig = name: keyboard:
    pkgs.writeTextFile {
      name = "${mkName name}-config.kdb";
      text = ''
        (defcfg
          ${keyboard.extraDefCfg}
          ${mkDevices keyboard.devices}
          linux-continue-if-no-devs-found yes)

        ${keyboard.config}
      '';
      checkPhase = ''
        ${getExe cfg.package} --cfg "$target" --check --debug
      '';
    };

  # Recommended user service (based on official docs)
  mkService = name: keyboard:
    nameValuePair (mkName name) {
      Unit = {
        Description = "Kanata keyboard remapper - ${name}";
      };
      Service = {
        Type = "simple";
        ExecStart = ''
          ${getExe cfg.package} \
            --cfg ${keyboard.configFile} \
            --no-wait \
            ${optionalString (keyboard.port != null) "--port ${toString keyboard.port}"} \
            ${escapeSystemdExecArgs keyboard.extraArgs}
        '';
        Restart = "on-failure";
        RestartSec = 3;
      };
      Install = {
        WantedBy = ["default.target"];
      };
    };

  mkKbdFile = name: keyboard: let
    _name = mkName name;
    kbdFile = "${_name}.kbd";
    serviceFile = "${_name}.service";
  in
    nameValuePair "${configDir}/${kbdFile}" {
      source = mkConfig name keyboard;
      onChange = ''
        systemctl --user restart ${serviceFile} || true
      '';
    };
in {
  options.services.kanata = {
    enable = mkEnableOption "kanata, a tool to improve keyboard comfort and usability with advanced customization";
    package = mkPackageOption pkgs "kanata" {
      example = ["kanata-with-cmd"];
      extraDescription = ''
        ::: {.note}
        If {option}`danger-enable-cmd` is enabled in any of the keyboards, the
        `kanata-with-cmd` package should be used.
        :::
      '';
    };
    keyboards = mkOption {
      type = with types; attrsOf (submodule keyboard);
      default = {};
    };
    generateKbdFilesOnly = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Only generate the kbd config files without creating systemd services.
        Useful for sharing the generated file with other systems (e.g. Windows via WSL symlink).
      '';
    };
  };

  config = mkIf cfg.enable {
    warnings = let
      keyboardsWithEmptyDevices = filterAttrs (_name: keyboard: keyboard.devices == []) cfg.keyboards;
      existEmptyDevices = length (attrNames keyboardsWithEmptyDevices) > 0;
      moreThanOneKeyboard = length (attrNames cfg.keyboards) > 1;
    in
      optional (existEmptyDevices && moreThanOneKeyboard)
      "One device can only be intercepted by one kanata instance.  Setting services.kanata.keyboards.${head (attrNames keyboardsWithEmptyDevices)}.devices = [ ] and using more than one services.kanata.keyboards may cause a race condition.";

    home = {
      file = mapAttrs' mkKbdFile cfg.keyboards;
      packages = [cfg.package];
    };

    systemd.user.services =
      mkIf (!cfg.generateKbdFilesOnly)
      (mapAttrs' mkService cfg.keyboards);
  };
}
